version: '3.9'

services:
  gdrag-bot-app:
    extends:
      file: docker-compose.yml
      service: gdrag-bot-app
    environment:
      OLLAMA_HOST: ollama-container
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    depends_on:
      - gdrag-bot-db
      - ollama-container
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  gdrag-bot-db:
    extends:
      file: docker-compose.yml
      service: gdrag-bot-db

secrets:
  postgres_db:
    file: ./data/pgvector/local-db.txt
  postgres_user:
    file: ./data/pgvector/local-user.txt
  postgres_password:
    file: ./data/pgvector/local-password.txt
