version: '3.9'

services:
  gdrag-bot-app:
    image: gdrag-bot:latest
    command: streamlit run app/main.py --server.port 8080
    volumes:
      - ./app/:/app/demo_app
    ports:
      - 8080:8080
    environment:
      - OLLAMA_HOST=host.docker.internal
