version: '3'

services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  gdrag-bot-app:
    image: gdrag-bot:latest
    command: streamlit run app/main.py --server.port 8080
    volumes:
      - ./app/:/app/demo_app
    ports:
      - 8080:8080
